import unittest

from modules.bi_workbook_layout import (
    normalize_bi_shop_daily,
    normalize_bi_traffic,
    resolve_bi_workbook_layout,
)


class BusinessInsightsWorkbookLayoutTest(unittest.TestCase):
    def _daily_sheet(self, sales, orders):
        return [
            ["Overview"],
            ["Date","Sales (VND)","Orders","Product Clicks","Visitors","Order Conversion Rate"],
            ["01-09-2026-02-09-2026",sales*2,orders*2,20,20,"10%"],
            [None,None,None,None,None,None],
            ["Date","Sales (VND)","Orders","Product Clicks","Visitors","Order Conversion Rate"],
            ["01-09-2026",sales,orders,10,10,"10%"],
        ]

    def _traffic_summary(self, sales):
        return [
            ["Product Card"],
            ["Traffic Source","Sales Ratio","Sales (VND)","Product Impressions","Product Clicks","Orders","Units","CTR","Order Conversion Rate","Sales per Order","Buyers","Unique Product Impressions","Unique Product Clicks"],
            ["Search","100%",sales,100,10,2,2,"10%","20%",sales/2,2,80,8],
        ]

    def _traffic_daily(self, sales):
        return [
            ["Product Card"],
            ["Traffic Source","Sales Ratio","Sales (VND)","Product Impressions","Product Clicks","Orders","Units","CTR","Order Conversion Rate","Sales per Order","Buyers","Unique Product Impressions","Unique Product Clicks"],
            ["Product Card","100%",sales,100,10,2,2,"10%","20%",sales/2,2,80,8],
            ["01-09-2026","100%",sales/2,50,5,1,1,"10%","20%",sales/2,1,40,4],
        ]

    def _workbook(self):
        # Absolute positions are intentionally non-legacy. Role-relative stage
        # order remains placed -> confirmed -> paid.
        return [
            [["Shopee Business Insights"]],
            self._daily_sheet(1000,2),
            self._traffic_summary(1000),
            [["Overview / generated by Shopee"]],
            self._traffic_daily(1000),
            self._daily_sheet(900,2),
            [["Spacer"]],
            self._traffic_summary(900),
            self._traffic_daily(900),
            self._daily_sheet(800,2),
            self._traffic_summary(800),
            [["Another overview"]],
            self._traffic_daily(800),
        ]

    def test_resolves_roles_by_content_not_absolute_sheet_index(self):
        resolved=resolve_bi_workbook_layout(self._workbook())
        self.assertEqual(resolved["sourceIndices"]["shopDaily"],[1,5,9])
        self.assertEqual(resolved["sourceIndices"]["trafficSummary"],[2,7,10])
        self.assertEqual(resolved["sourceIndices"]["trafficDaily"],[4,8,12])

    def test_reordered_workbook_normalizes_same_stage_semantics(self):
        sheets=self._workbook()
        shop=normalize_bi_shop_daily(sheets,shop_id="SHOP_X")
        traffic_daily,traffic_monthly=normalize_bi_traffic(
            sheets,shop_id="SHOP_X",data_month="2026-09"
        )
        self.assertEqual(len(shop),3)
        self.assertEqual([x["order_stage"] for x in shop],["placed","confirmed","paid"])
        self.assertEqual([x["gross_sales"] for x in shop],[1000,900,800])
        self.assertEqual(len(traffic_daily),3)
        self.assertEqual(len(traffic_monthly),3)
        self.assertEqual([x["order_stage"] for x in traffic_daily],["placed","confirmed","paid"])
        self.assertEqual([x["sales"] for x in traffic_monthly],[1000,900,800])

    def test_missing_required_role_fails_closed(self):
        sheets=self._workbook()[:-1]
        with self.assertRaises(ValueError):
            resolve_bi_workbook_layout(sheets)


if __name__=="__main__":
    unittest.main()
